name: Build and deploy docker images

on: 
  push:
    branches:
      - main

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
  
      - name: Login to docker
        uses: docker/login-action@v3
        with:
            username: ${{ secrets.DOCKER_USERNAME }}
            password: ${{ secrets.DOCKER_PASSWORD }}
  
      - name: Build docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/todo-back:latest ./backend
  
      - name: Push to dockerhub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/todo-back:latest 

  deploy-to-ec2:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Add ssh key
        run: echo "${{ secrets.EC2_SECRET_KEY }}" > ec2_key.pem && chmod 600 ec2_key.pem
      
      - name: Deploy to ec2
        run: |
          ssh -o StrictHostKeyChecking=no -i ec2_key.pem ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << EOF
            docker stop todo-back || true
            docker rm todo-back || true
            docker system prune -f
            docker pull ${{ secrets.DOCKER_USERNAME }}/todo-back:latest
            docker run -d --name todo-back -p 80:3000 ${{ secrets.DOCKER_USERNAME }}/todo-back:latest
          EOF
      
